# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: deps:node:server,package_manager:yarn:
version: 2.1

jobs:
  test-job:
    working_directory: /client
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Run tests
          command: yarn test
      - store_test_results:
          path: test-results
  deploy-server-job:
    working_directory: /server
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # Replace this with steps to build a package, or executable
      - run:
          name: Deploy server
          command: yarn run start-server
  build-client-job:
    working_directory: "/client"
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Build UI
          command: yarn build

workflows:
  deploy-server:
    jobs:
      - deploy-server-job

  deploy-client:
    jobs:
      - test-job
      - build-client-job:
          requires:
            - test-job
