# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: deps:node:server,package_manager:yarn:
version: 2.1

docker-node: &docker-node
  docker:
    - image: cimg/node:20.11.1

git-checkout: &git-checkout
  checkout:
    path: ~/scavenger-hunt

yarn-install-step: &yarn-install-step
  run:
    name: Yarn install
    command: yarn install

jobs:
  ui-test-job:
    <<: *docker-node
    working_directory: ~/scavenger-hunt/client
    parallelism: 4
    steps:
      - <<: *git-checkout
      - <<: *yarn-install-step
      - run:
          name: Run tests
          command: yarn test
      - store_test_results:
          path: ui-test-results
  # deploy-server-job:
  #   <<: *docker-node
  #   working_directory: ~/scavenger-hunt/server
  #   parallelism: 4
  #   steps:
  #     - <<: *git-checkout
  #     - <<: *yarn-install-step
  #     - run:
  #         name: Deploy server
  #         command: yarn run start-server
  # build-client-job:
  #   <<: *docker-node
  #   working_directory: ~/scavenger-hunt/client
  #   parallelism: 4
  #   steps:
  #     - <<: *git-checkout
  #     - <<: *yarn-install-step
  #     - run:
  #         name: Build UI
  #         command: cd client && yarn build
  # deploy-client-job:
  #   <<: *docker-node
  #   working_directory: ~/scavenger-hunt/client
  #   parallelism: 4
  #   steps:
  #     - <<: *git-checkout
  #     - <<: *yarn-install-step

workflows:
  tests:
    jobs:
      - ui-test-job
  # deploy-server:
  #   environment:
  #     NODE_ENV: production
  #   jobs:
  #     - deploy-server-job
  # deploy-client:
  #   environment:
  #     NODE_ENV: production
  #   jobs:
  #     - ui-test-job
  #     - build-client-job:
  #         requires:
  #           - ui-test-job
  #     - deploy-client-job:
  #         requires:
  #           - build-client-job
