# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: deps:node:server,package_manager:yarn:
version: 2.1

docker-node: &docker-node
  docker:
    - image: cimg/node:21.7.1

git-checkout-root: &git-checkout-root
  checkout:
    path: ~/scavenger-hunt

yarn-install-step: &yarn-install-step
  run:
    name: Yarn install
    no_output_timeout: 30m
    command: yarn install --frozen-lockfile

jobs:
  test-ui-job:
    <<: *docker-node
    working_directory: ~/scavenger-hunt/client
    parallelism: 2
    steps:
      - <<: *git-checkout-root
      - <<: *yarn-install-step
      - run:
          name: UI functional tests
          command: yarn test
      # - run:
      #     name: UI e2e tests
      #     command: yarn playwright
      - store_test_results:
          path: ui-test-results

  deploy-server-job:
    <<: *docker-node
    working_directory: ~/scavenger-hunt/server
    parallelism: 2
    steps:
      - <<: *git-checkout-root
      - <<: *yarn-install-step
      - run:
          name: Graphql codegen
          command: yarn codegen
      - run:
          name: Compile
          command: yarn compile
      - run:
          name: Deploy server via webhook
          command: curl ${DEPLOY_SERVER_WEBHOOK}
  deploy-ui-job:
    <<: *docker-node
    working_directory: ~/scavenger-hunt/client
    parallelism: 5
    steps:
      - <<: *git-checkout-root
      - <<: *yarn-install-step
      - run:
          name: Build UI & Storybook
          command: yarn build && yarn build-storybook
      - run:
          name: Deploy UI
          command: curl ${DEPLOY_UI_WEBHOOK}
      - run:
          name: Deploy Storybook
          command: curl ${DEPLOY_STORYBOOK_WEBHOOK}

workflows:
  test:
    jobs:
      - test-ui-job
  deploy:
    when:
      equal: [master, << pipeline.git.branch >>]
    jobs:
      - deploy-server-job
      - deploy-ui-job:
          requires:
            - deploy-server-job
