# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: deps:node:server,package_manager:yarn:
version: 2.1

orbs:
  node: circleci/node

jobs:
  test-job:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: cd client && yarn test
      - store_test_results:
          path: test-results
  # deploy-server-job:
  #   executor: node/default
  #   steps:
  #     - checkout
  #     - node/install-packages:
  #         pkg-manager: yarn
  #     - run:
  #         name: Deploy server
  #         command: cd server && yarn run start-server
  # build-client-job:
  #   executor: node/default
  #   steps:
  #     - checkout
  #     - node/install-packages:
  #         pkg-manager: yarn
  #     - run:
  #         name: Build UI
  #         command: cd client && yarn build

workflows:
  test:
    jobs:
      - test-job
  # deploy-server:
  #   environment:
  #     NODE_ENV: production
  #   jobs:
  #     - deploy-server-job

  # deploy-client:
  #   environment:
  #     NODE_ENV: production
  #   jobs:
  #     - test-job
  #     - build-client-job:
  #         requires:
  #           - test-job
