# See: https://circleci.com/docs/configuration-reference
# The DEPLOY jobs end with a deploy to Render.com via webhook.
# The steps before the deploy webhook have no impact on the actual
# deploy process, as Render will run those same commands during its
# deploy process. Those steps are run here so I can potentially
# catch any issues before the deploy webhook is called.

version: 2.1

docker-node: &docker-node
  docker:
    - image: cimg/node:20.11.1

git-checkout-root: &git-checkout-root
  checkout:
    path: ~/scavenger-hunt

yarn-install-step: &yarn-install-step
  run:
    name: Yarn install
    no_output_timeout: 30m # just in case Render has a slow environment
    command: yarn install --frozen-lockfile

jobs:
  test-ui-job:
    <<: *docker-node
    working_directory: ~/scavenger-hunt/client
    parallelism: 2
    steps:
      - <<: *git-checkout-root
      - <<: *yarn-install-step
      - run:
          name: UI functional tests
          command: yarn test
      # - run:
      #     name: UI e2e tests
      #     command: yarn playwright
      - store_test_results:
          path: ui-test-results

  deploy-server-job:
    <<: *docker-node
    working_directory: ~/scavenger-hunt/server
    parallelism: 2
    steps:
      - <<: *git-checkout-root
      - <<: *yarn-install-step
      - run:
          name: Graphql codegen
          command: yarn codegen
      - run:
          name: Compile TS
          command: yarn compile
      - run:
          name: Deploy server via webhook
          command: curl ${DEPLOY_SERVER_WEBHOOK}
  deploy-ui-job:
    <<: *docker-node
    working_directory: ~/scavenger-hunt/client
    parallelism: 2
    steps:
      - <<: *git-checkout-root
      - <<: *yarn-install-step
      - run:
          name: Build UI
          command: yarn build
      - run:
          name: Deploy UI
          command: curl ${DEPLOY_UI_WEBHOOK}
      - run:
          name: Build Storybook
          command: yarn build-storybook
      - run:
          name: Deploy Storybook
          command: curl ${DEPLOY_STORYBOOK_WEBHOOK}

workflows:
  test:
    jobs:
      - test-ui-job
  deploy:
    when:
      equal: [<< pipeline.git.branch >>, master]
    jobs:
      - deploy-server-job
      - deploy-ui-job:
          requires:
            - deploy-server-job
